# Generated by Django 4.2.5 on 2023-10-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_delete_projectsinportfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='active',
            new_name='is_active',
        ),
    ]
