# Generated by Django 4.2.5 on 2023-10-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_rename_active_portfolio_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='is_active',
            new_name='active',
        ),
    ]
