# Generated by Django 4.2.5 on 2023-10-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_rename_is_active_portfolio_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='contactEmail',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='active',
            new_name='is_active',
        ),
    ]
